[build]
  command = "pip install -r requirements.txt && alembic upgrade head"
  publish = "."

[build.environment]
  PYTHON_VERSION = "3.11"
  DATABASE_URL = "sqlite:///./prod.db"

[functions]
  included_files = ["app/**", "alembic/**", "alembic.ini"]

[dev]
  command = "uvicorn app.main:app --host 0.0.0.0 --port 8000"
  targetPort = 8000
  publish = "."

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/main"
  status = 200
